name: Scheduled Prompt Optimization

on:
  # Run every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  optimize_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Prompt Optimization Script
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python scripts/optimize_prompt.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'MLOps: Auto-updated master_prompt.json based on user feedback.'
          file_pattern: |
            data/master_prompt.json
            data/feedback_log.json